### PR TITLE
0.15

### PR DESCRIPTION
**Pull request by endel**
Work in progress! 🙈🙈 

**Preview:** https://deploy-preview-90--colyseus-docs.netlify.app/colyseus/migrating/0.15/

---

Missing documentation updates:
- https://github.com/colyseus/colyseus/pull/459
- https://github.com/colyseus/colyseus/pull/454

### CODE REVIEW

**Comment by based64-eth** [comment]
wen?

**Comment by CocosGames** [comment]
cn version will be pulled later today.

**Comment by CocosGames** [comment]
> cn version will be pulled later today.

maybe tommorrow...

**Comment by endel** [comment]
hi @CocosGames, we've made a few changes to the sidebar, e.g. added a "Dev Mode" page, and a "More" section, when you have some time could you please review if changes are necessary for the translated pages?

**Comment by CocosGames** [comment]
You got it.👌

**Comment by endel** [comment]
@CocosGames this pull-request shouldn't have been merged yet. I've just reverted the PR to avoid docs for 0.15 going live. We'll need to figure out how to re-open the PR as we had before now.

**Comment by CocosGames** [comment]
Sorry about that, I'll resubmit a pr we need.

**Pull request merged**
