### PR TITLE
Continuous Proofreading

### PR DESCRIPTION
**Pull request by CocosGames**
- Sentence fluentment / bug fix
- Traditional Chinese sync with SChinese
- Traditional Chinese specific words
~- Official updates~

### CODE REVIEW

**Comment by CocosGames** [comment]
This branch has no conflicts with the base branch, but all checks have failed. Why? @endel

**Comment by endel** [comment]
Thanks for noticing @CocosGames, apparently this already started happening a few days ago (this contribution also didn't get deployed properly) https://github.com/colyseus/docs/commit/bfa531f3dabe53d411fe56e4182acf5bc2bcf3e6

The build integration with Netlify stopped working for some reason, we need to investigate that.

**Comment by endel** [comment]
Hi @CocosGames, the build issue has been fixed here, can you try again with the latest commits? 😇  https://github.com/colyseus/docs/commit/a8ff4a3f0ab313a2037cb4e020c9adf6fa944462

**Comment by CocosGames** [comment]
Seems good, thank you @endel .

**Pull request closed without merging**
