### PR TITLE
Pokemon Auto Chess in community game page

### PR DESCRIPTION
**Pull request by keldaan-ag**
add my game in the community page

### CODE REVIEW

**Comment by Wenish** [comment]
one note to add. nintendo dosnt like others to use their trademarks. so i would not promote this.

**Comment by endel** [comment]
For the purpose of games made with Colyseus, especially for being open-source, @keldaan-ag's project is a great fit to demonstrate there. I don't see that section as "promotion" but as a collaborative wiki for the community. 

(If the project gets taken down for using Nintendo's IP, the source code would still be valuable for the community to have a look)

**Comment by Wenish** [comment]
yeah. my information is just from reading news that nitendo is really harsh on community projects.
i dont hold back to sending lawyers.

**Comment by keldaan-ag** [comment]
I am aware that my project can end at every moment. If Nintendo wants me to stop, i'll stop in the next minute.

@Wenish thanks for you advice, i have not contacted Nintendo, nor did they. As a backend software engineer, i have no experience in this kind of stuff. For me, its more of a side project that occupy my free time.

I have started Pokemon Auto Chess in 2019 knowing the risks that everything can stop at any moment. I have tried to limit those by keeping everything open-source and non profit but of course, i have no rights, and the Pokemon Company can decide the fate of this project at any moment.

As @endel said, if the project gets taken down by Nintendo, the source code could still be valuable.

I made this PR with the sole idea that it could be interesting to others if they want to have a look.

I have deleted this PR. I can make a new one if you want, maybe with some kind of [Fan game] mention/disclaimer

**Pull request closed without merging**
