### PR TITLE
Remove playersByClientId reference, add a comment to main doc

### LINKED ISSUE #22: Clarify `playersByClientId` on onMessage
https://github.com/colyseus/docs/blob/master/docs/server/room.md#onmessage-client-data

### PR DESCRIPTION
**Pull request by minviable**
Closes #22 
Verbose point about using Room State as a suggested way to maintain states

### CODE REVIEW

**Comment by endel** [comment]
Thanks for the PR @minviable 

I was thinking on adding also `onJoin()` creating the player instance, I like the note you've added at the bottom with more info about the state

```typescript
onJoin(client, options) {
  this.state.players[client.sessionId] = new Player()
}

onMessage(client, message) {
  const player = this.state.players[client.sessionId];
  // ...
}
```

What do you think?

**Comment by minviable** [comment]
> Thanks for the PR @minviable
> ...
> What do you think?

Honestly, i am not sure - i think when we add disparate concepts to mini examples it can detract from the crux of the matter.

Let me take another look see if we can make this a bit simpler

**Comment by minviable** [comment]
Let's move the example down to the bottom of the section and provide a functioning demo. 
It can implement both methods you've mentioned and an example 'state'.

What do you think?
With code comments i can highlight which areas to concentrate on - and at the same time show how it all fits together.. ?

**Comment by minviable** [comment]
@endel etc
Is this too much?
```
import { Room, Client } from "colyseus";
import { Schema, MapSchema, type } from "@colyseus/schema";

// An abstract player object, demonstrating a potential 3D world position
export class Player {
    clientId: string = "";
    x: number = 0.11;
    y: number = 2.22;
    z: number = 33.33;
}

// Our custom game state, an ArraySchema of type Player only at the moment
export class State extends Schema {
    @type({ map: "string" })
    players = new MapSchema<boolean>();
}

export class TestRoom extends Room<State, Player> {

    // Colyseus will invoke when creating the room instance
    onCreate(options: any) {
        // initialize empty room state
        this.setState(new State());
    }

    // Called every time a client joins
    onJoin(client: Client, options: any) {
        this.state.players[client.sessionId] = new Player();
    }

    // Called every time this room receives a message
    onMessage(client: Client, message: any) {
        const player = this.state.players[client.sessionId];

        // Pretend that we sent the room the message:
        // {command: "left"}
        if (message.command === "left") {
            player.x -= 1;
        } else if (message.command === "right") {
            player.x += 1;
        }

        console.log("x: " + player.x, "y: " + player.y , "z: " + player.z);
    }
}
```

**Comment by endel** [comment]
It's a bit large, but I think it's ok! I'd just remove the `clientId` property from `Player` on this demo! Thanks!

**Comment by endel** [comment]
Oh, and also, use `MapSchema<Player>` instead of `MapSchema<boolean>` 👀

**Comment by minviable** [comment]
Isn't it `client.id` ?
why would i use `sessionId` instead of `.id` ?

**Comment by minviable** [comment]
I think the 'example' heading needs to appear in menu - not sure how

**Comment by endel** [comment]
Awesome, thanks for the typo and grammar changes @minviable! 🎉 

PS: `client.id` is an alias to `client.sessionId` now. It used to be different in previous versions but it caused problems. I'm thinking on removing `client.id` on next versions, as `client.sessionId` makes it more clear that the id is ephemeral - not really a reliable user identifier, as when user connects to other rooms, the id will be different.

**Pull request merged**
